# Generated by Django 4.2.28 on 2026-02-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "offres",
            "0004_alter_candidature_id_alter_da_id_alter_entreprise_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="da",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="offre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
